[versions]
java = "24"
javaToolchain = "24"
kotlin = "2.3.10"
apollo = "4.4.1"
ktor = "3.4.0"
activity = "1.12.4"
appcompat = "1.7.1"
agp = "9.0.1"
jackson = "2.21.0"
compose = "1.10.1"
protoBuf = "4.34.0"
lifecycle = "2.10.0"
jooq = "3.20.11"
nav3 = "1.0.1"
jetbrainsNav3 = "1.0.0-alpha06"
coil3 = "3.4.0"
zoomable = "2.11.1"
okhttp = "5.3.2"
paparazzi = "2.0.0-alpha04"
composablePreviewScanner = "0.8.1"

[plugins]
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.require = "14.0.1" }
kobylynskyi-graphqlCodegen = { id = "io.github.kobylynskyi.graphql.codegen", version.require = "5.10.1-BUILD-2dd014e63d18dcb3c0fcd704b1f3b6db2ac18b1e" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
protobuf = { id = "com.google.protobuf", version.require = "0.9.6" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }

[libraries]
kotlinRefrect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.require = "1.10.2" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.require = "0.7.1-0.6.x-compat" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.require = "1.10.0" }

# Plugin
androidGradlePlugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "agp" }

# Jooq
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jooqKotlin = { module = "org.jooq:jooq-kotlin", version.ref = "jooq" }
jooqCodegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
jooqMeta = { module = "org.jooq:jooq-meta", version.ref = "jooq" }

# ProtoBuf
protobufProtobufJavalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protoBuf" }
protobufProtoc = { module = "com.google.protobuf:protoc", version.ref = "protoBuf" }

# Ktor
ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerEngine = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktorServerCors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktorServerDefaultHeaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktorServerFowardedHeader = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktorServerCompression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktorSerializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorServerContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktorServerCallLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientJs = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Apollo
apolloRuntime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apolloNormalizedCache = { module = "com.apollographql.apollo:apollo-normalized-cache", version.ref = "apollo" }
apolloAdapters = { module = "com.apollographql.adapters:apollo-adapters-kotlinx-datetime", version = "0.7.0" }
apolloAdaptersCore = { module = "com.apollographql.adapters:apollo-adapters-core", version = "0.7.0" }

# Jackson
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

# WebAUth4J
webauth4jCore = { module = "com.webauthn4j:webauthn4j-core", version.require = "0.31.0.RELEASE" }

opentelemetryApi = { module = "io.opentelemetry:opentelemetry-api", version.require = "1.58.0" }

# Android
androidActivityActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidAppCompatAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.require = "1.17.0" }
androidxLifecycleViewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidxLifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidxLifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidxNavigation3Runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3" }
androidxNavigation3Ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3" }
jetbrainsNavigation3Ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "jetbrainsNav3" }
androidxComposeSaveable = { module = "androidx.compose.runtime:runtime-saveable", version = "1.10.4" }
composeUiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
composeUiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }

# Test
kotestRunnerJunit5 = { module = "io.kotest:kotest-runner-junit5", version.require = "6.1.3" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
composablePreviewScanner = { module = "io.github.sergio-sastre.ComposablePreviewScanner:android", version.ref = "composablePreviewScanner" }

# Mail
jakarta-mail-api = { module = "jakarta.mail:jakarta.mail-api", version.require = "2.1.5" }
jakarta-mail = { module = "org.eclipse.angus:jakarta.mail", version.require = "2.0.5" }
angus-mail = { module = "org.eclipse.angus:angus-mail", version.require = "2.0.5" }
jakarta-activation-api = { module = "jakarta.activation:jakarta.activation-api", version.require = "2.1.4" }

# Koin
koinCore = { module = "io.insert-koin:koin-core", version.require = "4.1.1" }

# Coil
coilRuntime = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
coilCompose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coilNetworkKtor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coilNetworkOkhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }

# Log
log4j-api = { module = "org.slf4j:slf4j-api", version.require = "2.0.17" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.require = "1.5.29" }
logstashLogbackEncoder = { module = "net.logstash.logback:logstash-logback-encoder", version.require = "9.0" }

# Graphql
graphqlJava-extendedScalars = { module = "com.graphql-java:graphql-java-extended-scalars", version.require = "2023-01-24T02-11-56-babda5f" }
graphqlJava = { module = "com.graphql-java:graphql-java", version.require = "25.0" }
graphqlJavaKickstart-JavaTools = { module = "com.graphql-java-kickstart:graphql-java-tools", version.require = "14.0.1" }

# DataStore
androidxDatastoreDatastore = { module = "androidx.datastore:datastore", version.require = "1.2.0" }

# Other
jedis = { module = "redis.clients:jedis", version.require = "7.3.0" }
jsoup = { module = "org.jsoup:jsoup", version.require = "1.22.1" }
hikariCP = { module = "com.zaxxer:HikariCP", version.require = "7.0.2" }
mariadbClient = { module = "org.mariadb.jdbc:mariadb-java-client", version.require = "3.5.7" }

# Play
androidxCredentialsPlayServicesAuth = { module = "androidx.credentials:credentials-play-services-auth", version.require = "1.5.0" }
androidxCredentials = { module = "androidx.credentials:credentials", version.require = "1.5.0" }
